add: --line

diff --git a/xmas b/xmas
--- a/xmas
+++ b/xmas
@@ -1,9 +1,8 @@
 #!/usr/bin/env bash
 
-# set -euo pipefail
-# set -x
+set -euo pipefail
 
-version="0.0.1"
+version="0.0.2"
 
 star='\e[33m★\e[m'
 left='\e[32m／\e[m'
@@ -18,11 +17,12 @@ $0 -- Plant X'mas tree(s)
 Usage: $0 [options]
 
 Options:
- -s, --size <POSITIVE SIZE>  game level (default=5)
- -n, --number <POSITIVE NUM> number of tree (default=1)
- -a, --animation             enable animation
- -i, --interval <NUM>        animation interval (default=1)
- -m, --monochrome            disable color
+ -s, --size <POSITIVE INT>    game level (default=5)
+ -n, --number <POSITIVE INT>  number of tree (default=1)
+ -l, --line <POSITIVE INT>    number of line (default=1)
+ -a, --animation              enable animation
+ -i, --interval <NATURAL INT> animation interval (default=1)
+ -m, --monochrome             disable color
  -h, --help     display this help and exit
  -v, --version  output version infromation and exit
 
@@ -94,10 +94,20 @@ _print_tree() {
   )"
 }
 
+_mono(){
+  if [ "$1" = 1 ]; then
+    sed 's/\x1b\[[0-9;]*m//g'
+  else
+    cat
+  fi
+
+}
+
 main() {
-  local size number animation interval monochrome
+  local size number line animation interval monochrome
   size="5"
   number="1"
+  line="1"
   animation="0"
   interval="1"
   monochrome="0"
@@ -134,6 +144,15 @@ main() {
         shift 2
         s=1
         ;;
+      -l | --line)
+        if [[ -z $2 ]] || ! [[ $2 =~ ^[0-9]+$ ]] || [ "$2" -lt 1 ]; then
+          echo "error: option '$1' requires positive int -- $2" >&2
+          return 1
+        fi
+        line="$2"
+        shift 2
+        s=1
+        ;;
       -i | --interval)
         if [[ -z $2 ]] || ! [[ $2 =~ ^[0-9]+$ ]] || [ "$2" -lt 0 ]; then
           echo "error: option '$1' requires natural int -- $2" >&2
@@ -163,20 +182,18 @@ main() {
   done
   if [ "$animation" = "1" ]; then
     while :; do
-      if [ "$monochrome" = 1 ]; then
-        _print_tree "$size" "$number" | sed 's/\x1b\[[0-9;]*m//g'
-      else
-        _print_tree "$size" "$number"
-      fi
+      for i in $(eval echo {1.."$line"}); do
+        _print_tree "$size" "$number" | _mono "$monochrome"
+      done
       sleep "$interval"s
-      echo -ne "\\e[$((size + 3))A"
+      for i in $(eval echo {1.."$line"}); do
+        echo -ne "\\e[$((size + 3))A"
+      done
     done
   else
-    if [ "$monochrome" = 1 ]; then
-      _print_tree "$size" "$number" | sed 's/\x1b\[[0-9;]*m//g'
-    else
-      _print_tree "$size" "$number"
-    fi
+     for i in $(eval echo {1.."$line"}); do
+       _print_tree "$size" "$number" | _mono "$monochrome"
+     done
   fi
 }
 
